<a href="https://colab.research.google.com/github/SihyunPark01/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
"""
날짜 : 21/10/18
이름 : 박시현
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
- 고성능의 수치계산을 위한 파이썬 라이브러리
- 파이썬의 기본 리스트보다 월등한 연산의 성능 제공
- 행렬이나 대규모 다차원 배열 처리를 지원

"""
import numpy as np


In [10]:
# numpy 벡터 --- 파이썬의 리스트구조와 비슷함.
v1 = np.array([1,2,3,4,5])
print('v1 :', v1)

v2 = np.arange(5)
print('v2 :', v2)

v3 = np.arange(10)
print('v3 :', v3)

v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]


In [11]:
# 0~1 사이의 임의의 실수 100개
result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.randn(100)

# 0~9 사이의 임의의 정수
result3 = np.random.randint(10)

In [12]:
result1, result2, result3

(array([0.65460695, 0.82113253, 0.97536463, 0.02524442, 0.19032929,
        0.03348174, 0.61023349, 0.33714842, 0.35424405, 0.54439113,
        0.54903077, 0.87677677, 0.67689885, 0.31537043, 0.2839363 ,
        0.60487211, 0.84123499, 0.12980466, 0.27089849, 0.54724253,
        0.83753178, 0.87770132, 0.98376973, 0.54713286, 0.74939303,
        0.55188769, 0.98433039, 0.36594611, 0.0337532 , 0.7684726 ,
        0.90047067, 0.81302767, 0.23516301, 0.6599502 , 0.6504919 ,
        0.2094153 , 0.97887291, 0.17598077, 0.04199384, 0.47304518,
        0.51081365, 0.0892771 , 0.47532907, 0.46106059, 0.68089087,
        0.87789016, 0.57657652, 0.56921314, 0.43819885, 0.20487599,
        0.8604028 , 0.00159188, 0.95927852, 0.84965311, 0.34214873,
        0.14652722, 0.18955525, 0.82489262, 0.99829977, 0.25502147,
        0.81373734, 0.00571216, 0.09006172, 0.44416785, 0.23161785,
        0.40703904, 0.60622873, 0.83733162, 0.14584549, 0.16393473,
        0.77097466, 0.36043121, 0.21807986, 0.14

In [19]:
# numpy 행렬
m1 = np.array([[1,2],[3,4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.ones([2,4])
print(m3)

m4 = np.zeros([3,2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
# 행렬 인덱싱
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat)

print(mat[0, 0])          # 첫번째행의 첫번째열
print(mat[0, :])          # 첫번째행의 모든 열
print(mat[:, 0])          # 모든 행의 첫번째 열

print(mat[0:2, 0:2])      # 0~2행의 0~2열
print(mat[:, 0:2])        # 모든 행의 0~2열
print(mat[:, 2:4])        # 모든 행의 2~4열
print(mat[1:3, 1:3])      # 1~3행의 1~3열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
